library(rjags)
library(MCMCvis)
library(magrittr)

# Load data from "thk99buff.txt" and "thk99buff_n.txt"; this is the full dataset generated by the "complicated code" you saw in lab
thk99buff = read.delim("thk99buff.txt", sep="\t")
thk99buff_n = read.delim("thk99buff_n.txt", sep="\t") # Normalized data

regions = length(unique(thk99buff_n$region))
data = append(list(Nobs=nrow(thk99buff_n), Nregion=regions), thk99buff_n)

modelText = "model {
for (i in 1:Nobs) {
logWET.mu[i] <- b0[region[i]] + bRSLR[region[i]] * RSLR[i] + bWH[region[i]] * WH[i] + bTR[region[i]] * TR[i] #Linear Model
logWET[i] ~ dnorm(logWET.mu[i], logWET.tau) #Response distribution
logWET.p[i] ~ dnorm(logWET.mu[i], logWET.tau)
sq[i] <- (logWET[i]-logWET.mu[i])^2
sq.p[i] <- (logWET.p[i]-logWET.mu[i])^2
}

# Random Effect Priors
for(j in 1:Nregion) {
b0[j] ~ dnorm(b0.mu,b0.tau)
bRSLR[j] ~ dnorm(RSLR.mu,RSLR.tau)
bWH[j] ~ dnorm(WH.mu,WH.tau)
bTR[j] ~ dnorm(TR.mu,TR.tau)
}

# Hyper Priors
b0.mu ~ dnorm(0,0.00001)
b0.tau ~ dgamma(1,1)
RSLR.mu ~ dnorm(0,0.00001)
RSLR.tau ~ dgamma(1,1)
WH.mu ~ dnorm(0,0.00001)
WH.tau ~ dgamma(1,1)
TR.mu ~ dnorm(0,0.00001)
TR.tau ~ dgamma(1,1) 

#Fixed Effect Priors

logWET.tau ~ dgamma(1,1)

# P-values
p.min <- step(min(logWET.p[]) - min(logWET[]))
p.max <- step(max(logWET.p[]) - max(logWET[]))
p.range <- step((max(logWET.p[])-min(logWET.p[]))-(max(logWET[])-min(logWET[])))

p.mean <- step(mean(logWET.p[]) - mean(logWET[]))
p.sd <- step(sd(logWET.p[]) - sd(logWET[]))
p.fit <- step(sum(sq.p[])-sum(sq[]))
p.cv <- step((mean(logWET.p[])) - (mean(logWET[])))
}
"

model = jags.model(textConnection(modelText),
                   data = data,
                   n.chains=3,
                   n.adapt=10000) # Converges with 2000 adapt (adapt = burn-in)

output = coda.samples(model,
                      variable.names=c("b0", "bRSLR", "bWH", "bTR" ,"p.fit", "p.mean", "p.sd", "p.cv", "logWET.p"), # Same as OpenBUGS parameter tracking
                      n.iter=100000,
                      thin=1)

outputDir = "Results/PP-model58"
if (!dir.exists("Results"))
{
  dir.create("Results")
}
if (!dir.exists(outputDir))
{
  dir.create(outputDir)
}

save(output, file=sprintf("%s/PP-model58.RData", outputDir))


# Analysis ----------------------------------------------------------------

# All of the functions starting with "MCMC" come from the package "MCMCvis".
# Documentation can be found at https://github.com/caseyyoungflesh/MCMCvis, but I've included a summary:
# All MCMC vis functions accept the vector argument "params" which allows you to examine certain parameters.
# This is useful because you can track many parameters (4 watershed-level and 3 pvals, in this case), but only look at a few a time.
# This is most useful because tracking the predictive posterior generates 'n' posteriors, thus making a summary table at least 'n' long

# Posterior statistics (rounded)
MCMCsummary(output, params=c("p.fit", "p.mean", "p.sd"))
MCMCsummary(output, params=c("bWH"))

# Posterior statistics ("exact")
MCMCpstr(output, params=c("p.fit", "p.mean", "p.sd"), func = mean)
MCMCpstr(output, params=c("bWH"), func = median)$bWH

# Trace and density plot
MCMCtrace(output, params="p.fit", pdf=F)
MCMCtrace(output, params="bWH", ISB=F, pdf=F)

# Caterpillar plot (for comparing mixed-effect parameters)
# Not informative for p.fit because it's binary; see density plot above instead
MCMCplot(output, params=c("bWH"), ref_ovl = T)

# Extract predictive posterior summaries (slow at 100000 iterations)
ppredSummary = MCMCsummary(output, params="logWET.p") %>% data.frame()
names(ppredSummary) = c("mean", "sd", "q2.5", "median", "q97.5", "Rhat")

# Predictions vs Observed (1:1 plot)
rnge = c(-max(range(thk99buff$logWET)),max(range(thk99buff$logWET)))

plot(1~1, type="n",
     xlab = "Observed",
     ylab = "Predicted",
     xlim = range(thk99buff$logWET),
     ylim = rnge)
abline(0,1)

arrows(thk99buff$logWET, ppredSummary$q2.5, thk99buff$logWET, ppredSummary$q97.5, length=0.05, angle=90, code=3)
points(ppredSummary$mean~thk99buff$logWET, pch=21, col="black", bg="yellow")

# Predictive vs observed densities
ymax = max(density(ppredSummary$median)$y)
plot(density(thk99buff$logWET), ylim=c(0, ymax), main = "Pred Median vs Obs Posterior Densities", xlab = "Wetland Loss (log hectares)")
lines(density(ppredSummary$median), col="red")
lines(density(ppredSummary$q2.5), col="blue")
lines(density(ppredSummary$q97.5), col="green")
legend("topright", legend = c("Observed", "Pred Med", "Pred 2.5%", "Pred 97.5%"), col=c("black", "red", "blue", "green"), lty=1)


# Random n=200 Sample -----------------------------------------------------
preds = MCMCpstr(output, params="logWET.p")

set.seed(1337135)
random200 = sample(1:nrow(thk99buff), 200, replace=F)
plot(preds$logWET.p[random200]~thk99buff$logWET[random200],
     xlab = "Observed",
     ylab = "Predicted",
     xlim = range(thk99buff$logWET[random200]),
     ylim = range(thk99buff$logWET[random200]),
     pch=19, col = "#00000077")
abline(0,1)
